version: '3.3'
services: 
  backend:
    build: ./backend/
    ports: [3333:3333]
    restart: always
  frontend: 
    depends_on: [backend]
    build: ./frontend/
    ports: [3000:3000]
    restart: always
    

